function drawtabOne(hpanel,intmem,extmem,idatax,PC,cycle,ACC,B,PSW,SP,DPTR,Rn,C,flag,promem,branchNumber)
%Panel 1
    %First Line
    %Three control button
%     uicontrol(...
%         'Parent',hpanel,...
%         'Units','pixels',...
%         'Position',[20,430,140,20],...
%         'BackgroundColor',get(hpanel,'BackgroundColor'),...
%         'ForegroundColor','w',...
%         'HorizontalAlignment','center',...
%         'FontSize',11,...
%         'FontWeight','bold',...
%         'Style','text',...
%         'String','RESET');
    uicontrol(...
        'Parent',hpanel,...
        'Units','pixels',...
        'Position',[120,720,100,20],...
        'Style','pushbutton',...
        'Callback',{@Reset},...
        'String','RESET');
    
%     uicontrol(...
%         'Parent',hpanel,...
%         'Units','pixels',...
%         'Position',[20,430,140,20],...
%         'BackgroundColor',get(hpanel,'BackgroundColor'),...
%         'ForegroundColor','w',...
%         'HorizontalAlignment','center',...
%         'FontSize',11,...
%         'FontWeight','bold',...
%         'Style','text',...
%         'String','STEP');
    uicontrol(...
        'Parent',hpanel,...
        'Units','pixels',...
        'Position',[120,680,100,20],...
        'Style','pushbutton',...
        'Callback',{@Step},...
        'String','STEP');
    
    %Step number
    uicontrol(...
        'Parent',hpanel,...
        'Units','pixels',...
        'Position',[230,680,50,20],...
        'BackgroundColor',get(hpanel,'BackgroundColor'),...
        'ForegroundColor','w',...
        'HorizontalAlignment','center',...
        'FontSize',11,...
        'FontWeight','bold',...
        'Style','text',...
        'String','Step');
%     nstep_edit = uicontrol(...
%         'Parent',hpanel,...
%         'Units','pixels',...
%         'Position',[280,680,40,20],...
%         'Style','edit',...
%         'FontSize',11,...
%         'String','100');

    %run steps
    uicontrol(...
        'Parent',hpanel,...
        'Units','pixels',...
        'Position',[120,640,100,20],...
        'Style','pushbutton',...
        'Callback',{@RunSteps},...
        'String','RUN STEPS');
    StepsForOnce = uicontrol(...
        'Parent',hpanel,...
        'Units','pixels',...
        'Position',[230,640,50,20],...
        'Style','edit',...
        'FontSize',11);

    
%     uicontrol(...
%         'Parent',hpanel,...
%         'Units','pixels',...
%         'Position',[20,430,140,20],...
%         'BackgroundColor',get(hpanel,'BackgroundColor'),...
%         'ForegroundColor','w',...
%         'HorizontalAlignment','center',...
%         'FontSize',11,...
%         'FontWeight','bold',...
%         'Style','text',...
%         'String','RUN TO END');
    uicontrol(...
        'Parent',hpanel,...
        'Units','pixels',...
        'Position',[120,600,100,20],...
        'Style','pushbutton',...
        'Callback',{@RunToEnd},...
        'String','RUN TO END');
    %RunToEnd number
    uicontrol(...
        'Parent',hpanel,...
        'Units','pixels',...
        'Position',[230,600,50,20],...
        'BackgroundColor',get(hpanel,'BackgroundColor'),...
        'ForegroundColor','w',...
        'HorizontalAlignment','center',...
        'FontSize',11,...
        'FontWeight','bold',...
        'Style','text',...
        'String','Step');
    
    %special register
    %text displayed first
    handles.laxis = axes(...
        'Parent',hpanel,...
        'Units','normalized',...
        'Position',[0,0,1,1],...
        'visible','off');
    
    handles.tmp = text(...
        'String','ACC',...
        'Units','pixels',...
        'Position',[130,545],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontSize',11);
    handles.tmp = text(...
        'String','B',...
        'Units','pixels',...
        'Position',[130,520],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontSize',11);
    handles.tmp = text(...
        'String','C',...
        'Units','pixels',...
        'Position',[130,495],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontSize',11);
    handles.tmp = text(...
        'String','DPTR',...
        'Units','pixels',...
        'Position',[130,470],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontSize',11);
    handles.tmp = text(...
        'String','PC',...
        'Units','pixels',...
        'Position',[130,445],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontSize',11);
    handles.tmp = text(...
        'String','SP',...
        'Units','pixels',...
        'Position',[130,420],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontSize',11);
    handles.tmp = text(...
        'String','cycle',...
        'Units','pixels',...
        'Position',[130,395],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontSize',11);
    
    spec_table=uitable(...
        'Parent',hpanel,...
        'Units','pixels',...
        'Position',[160,365,73,207],...
        'ColumnWidth',{40},...
        'data',zeros(7,1),...
        'FontSize',11,...
        'columneditable',true,...
        'RearrangeableColumns','off'); 
    
    %Ri
    handles.tmp = text(...
        'String','Ri    R0     R1     R2     R3     R4     R5     R6     R7',...
        'Units','pixels',...
        'Position',[190,330],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontSize',11);
    
    Ri_table=uitable(...
        'Parent',hpanel,...
        'Units','pixels',...
        'Position',[20,260,352,47],...
        'ColumnWidth',{40},...
        'data',zeros(1,8),...
        'FontSize',11,...
        'columneditable',true,...
        'RearrangeableColumns','off');
    
    %PSW
    handles.tmp = text(...
        'String','PSW   CY     AC     f0      Rs1     Rs      OV      f1      P',...
        'Units','pixels',...
        'Position',[190,230],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontSize',11);
    
    PSW_table=uitable(...
        'Parent',hpanel,...
        'Units','pixels',...
        'Position',[20,160,352,47],...
        'ColumnWidth',{40},...
        'data',zeros(1,8),...
        'FontSize',11,...
        'columneditable',true,...
        'RearrangeableColumns','off');

    %ProgramMemory
    handles.tmp = text(...
        'String','CODE',...
        'Units','pixels',...
        'Position',[450,747],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontSize',11);
    ProgramMemory_table=uitable(...
        'Parent',hpanel,...
        'Units','pixels',...
        'Position',[390,20,143,707],...
        'ColumnWidth',{40},...
        'data',zeros(65535,1),...
        'FontSize',11,...
        'columneditable',true,...
        'RearrangeableColumns','off'); 
    
    %ExtraMemory
    handles.tmp = text(...
        'String','XDATA',...
        'Units','pixels',...
        'Position',[620,747],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontSize',11);
    ExtraMemory_table=uitable(...
        'Parent',hpanel,...
        'Units','pixels',...
        'Position',[560,20,143,707],...
        'ColumnWidth',{40},...
        'data',zeros(65535,1),...
        'FontSize',11,...
        'columneditable',true,...
        'RearrangeableColumns','off'); 
    
    %DATA
    handles.tmp = text(...
        'String','DATA/IDATA/SFR/IBT',...
        'Units','pixels',...
        'Position',[810,747],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontSize',11);
    DATA_table=uitable(...
        'Parent',hpanel,...
        'Units','pixels',...
        'Position',[740,220,123,507],...
        'ColumnWidth',{40},...
        'data',zeros(255,1),...
        'FontSize',11,...
        'columneditable',true,...
        'RearrangeableColumns','off'); 
    
    %SFR
    handles.tmp = text(...
        'String','SFR',...
        'Units','pixels',...
        'Position',[980,447],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontSize',11);
    SFR_table=uitable(...
        'Parent',hpanel,...
        'Units','pixels',...
        'Position',[920,220,123,207],...
        'ColumnWidth',{40},...
        'data',zeros(127,1),...
        'FontSize',11,...
        'columneditable',true,...
        'RearrangeableColumns','off'); 
    
    persistent c
        if isempty(c)
            c=0;
        end
    persistent Steps
        if isempty(Steps)
            Steps=0;
        end
    persistent EndSteps
        if isempty(EndSteps)
            EndSteps=0;
        end
    persistent RealRunNumber
        if isempty(RealRunNumber)
            RealRunNumber=0;
        end
    
    function Reset(hobj, evdt)
        set(spec_table,'data',zeros(7,1));
        set(Ri_table,'data',zeros(1,8));
        set(PSW_table,'data',zeros(1,8));
        set(ProgramMemory_table,'data',zeros(65535,1));
        set(ExtraMemory_table,'data',zeros(65535,1));
        set(DATA_table,'data',zeros(256,1));
        set(SFR_table,'data',zeros(128,1));
        set(handles.stepNumber,'String',0);  
%         [promem,extmem,intmem,idatax]=InitializeReg();
        [promem,extmem,intmem,idatax,PC,cycle,ACC,B,PSW,SP,DPTR,Rn,C,flag]=InitializeReg();
        c=0;
        Steps=0;
        EndSteps=0;
        set(handles.stepNumber,'String',c);
        set(handles.StepsOnceDisplay,'String',Steps);
        set(handles.StepsOnceDisplay,'String',EndSteps);
        set(handles.RunToEndNumber,'String',0);
    end

    handles.stepNumber = text(...
        'Units','pixels',...
        'Position',[305,691],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontWeight','bold',...
        'FontSize',11);

    function Step(hobj, evdt)
        [promem]=loadprogram(promem);
        branchNumber=c+1;
        [intmem,extmem,idatax,PC,cycle,ACC,B,PSW,SP,DPTR,Rn,C,flag]=startsim(promem,intmem,extmem,idatax,PC,cycle,ACC,B,PSW,SP,DPTR,Rn,C,flag,branchNumber);
        tempSpec=zeros(7,1);
        tempSpec(1,1)=ACC;
        tempSpec(2,1)=B;
        tempSpec(3,1)=C;
        tempSpec(4,1)=DPTR;
        tempSpec(5,1)=PC;
        tempSpec(6,1)=SP;
        tempSpec(7,1)=cycle;
        set(spec_table,'data',tempSpec);
        set(Ri_table,'data',Rn');
        set(PSW_table,'data',PSW');
        set(ProgramMemory_table,'data',promem);
        set(ExtraMemory_table,'data',extmem);
        set(DATA_table,'data',intmem);
        set(SFR_table,'data',idatax);
        c=c+1;
        str=sprintf('%d',c);
        set(handles.stepNumber,'String',c);
        
    end

    handles.StepsOnceDisplay = text(...
        'Units','pixels',...
        'Position',[305,651],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontWeight','bold',...
        'FontSize',11);
    
    function RunSteps(hobj, evdt)
        [promem]=loadprogram(promem);
        %[intmem,extmem,idatax,PC,cycle,ACC,B,PSW,SP,DPTR,Rn,C,flag]=startsim(promem,intmem,extmem,idatax,PC,cycle,ACC,B,PSW,SP,DPTR,Rn,C,flag);
        %         while (flag==0)
        StepsOnce = str2double(get(StepsForOnce,'String'))
        for i=1:StepsOnce
            branchNumber=Steps+StepsOnce;
            [intmem,extmem,idatax,PC,cycle,ACC,B,PSW,SP,DPTR,Rn,C,flag]=startsim(promem,intmem,extmem,idatax,PC,cycle,ACC,B,PSW,SP,DPTR,Rn,C,flag,branchNumber);
            cycle
            PC
        end
        tempSpec=zeros(7,1);
        tempSpec(1,1)=ACC;
        tempSpec(2,1)=B;
        tempSpec(3,1)=C;
        tempSpec(4,1)=DPTR;
        tempSpec(5,1)=PC;
        tempSpec(6,1)=SP;
        tempSpec(7,1)=cycle;
        set(spec_table,'data',tempSpec);
        set(Ri_table,'data',Rn');
        set(PSW_table,'data',PSW');
        set(ProgramMemory_table,'data',promem);
        set(ExtraMemory_table,'data',extmem);
        set(DATA_table,'data',intmem);
        set(SFR_table,'data',idatax);
        Steps=Steps+StepsOnce;
        str=sprintf('%d',Steps);
        set(handles.StepsOnceDisplay,'String',Steps);
        
    end

    handles.stepNumberEnd = text(...
        'Units','pixels',...
        'Position',[305,511],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontWeight','bold',...
        'FontSize',11);

    function RunToEnd(hobj, evdt)
%         [ACC,B,C,DPTR,PC,SP,cycle,Rn,PSW,ProgramMemory,ExternalDataMemory,InternalDataMemory,SpecialFunctionRegister]=getNum;
        [promem]=loadprogram(promem);
%         [intmem,extmem,idatax,PC,cycle,ACC,B,PSW,SP,DPTR,Rn,C,flag]=startsim(promem,intmem,extmem,idatax,PC,cycle,ACC,B,PSW,SP,DPTR,Rn,C,flag);
        i=0;
        branchNumber=1;
         while (PC<=943)
%        for i=1:200
            [intmem,extmem,idatax,PC,cycle,ACC,B,PSW,SP,DPTR,Rn,C,flag]=startsim(promem,intmem,extmem,idatax,PC,cycle,ACC,B,PSW,SP,DPTR,Rn,C,flag,branchNumber);
            i=i+1;
            branchNumber=branchNumber+1;
        end
        EndSteps=i;
        tempSpec=zeros(7,1);
        tempSpec(1,1)=ACC;
        tempSpec(2,1)=B;
        tempSpec(3,1)=C;
        tempSpec(4,1)=DPTR;
        tempSpec(5,1)=PC;
        tempSpec(6,1)=SP;
        tempSpec(7,1)=cycle;
        set(spec_table,'data',tempSpec);
        set(Ri_table,'data',Rn');
        set(PSW_table,'data',PSW');
        set(ProgramMemory_table,'data',promem);
        set(ExtraMemory_table,'data',extmem);
        set(DATA_table,'data',intmem);
        set(SFR_table,'data',idatax);       
        set(handles.stepNumberEnd,'String',EndSteps);
        set(handles.RunToEndNumber,'String',branchNumber);
    end

    handles.RunToEndNumber = text(...
        'Units','pixels',...
        'Position',[305,610],...
        'color','w',...
        'HorizontalAlignment','center',...
        'FontWeight','bold',...
        'FontSize',11);
    
set(gcf,'CloseRequestFcn','closereq')

end